const splashText: string[] = [
    "You can't fail classes you're not in, that's for sure.",
    "Steer clear of O-Chem, unless you fancy a challenge.",
    "Rec Sports fills up fast, even before the sun reaches its peak.",
    "Ah, Jendy's! A taste ever so refined.",
    "Fine dining at Jester City Limits, eh?",
    "Rec Sports fills up fast, even before the sun reaches its peak.",
    "RIP Domino, you beloved campus feline.",
    "The year is 2055 and Welch still isn't finished.",
    "Motivation dropping faster than ur GPA",
    "No Work Happens On PCL 5th Floor.",
    "I may be a sophomore in name, but my credit count screams freshman!",
    "Pain is temporary, GPA is forever.",
    "You've Yee'd Your Last Haw.",
    "lol everything is already waitlisted.",
    "At Least You're Not At A&M.",
    "TeXAs iS BaCK GuYZ",
    "mAke iT yOuR tExAS",
    "'Academically Challenged'",
    "Does McCombs teach Parseltongue?",
    "No Cruce Enfrente Del Bus.",
    "Omae Wa Mou Shindeiru...",
    "Bevo Bucks are the new Bitcoin",
    "Every day another brick disappears from Speedway",
    "The GDC will annex the EER one day",
    "Just you wait. Our CNS operatives will topple the EER regime",
    "To hike to Kins or not to hike to Kins...",
    "The road to Kinsolving is long, but their delicacies makes it worth every step.",
    "C'mon you Longhorns! You want to study forever?",
    "HOW BOUT A NICE CUP OF LIBER TEA",
    "It's called the quiet floor of the PCL for a reason",
    "'Whose car is this and why is it attempting to enter Welch?'",
    "'I really like one of my TAs and I wanna ask her out after this semester ends'",
    "CaN YoU aSk OuT a tA aFtEr tHe SeMeStEr Is oVeR AnD gRaDeS ArE DoNe?",
    "The Block of Butter incident of '22",
    "Arrows of Christ vs Church of Scientology was the crossover we didn't know we needed",
    "THE WALK SIGN IS ON TO CROSS GUADALUPE AND 21ST",
    "Days since last GDC door alarm: 0"
  ];
  
  export default splashText;
  