/**
 * A field of study (department) in UT's course schedule, i.e. `{ code: 'C S', name: 'Computer Science' }`
 */
export type FieldOfStudy = {
    /** The department code UT uses in the course schedule, i.e. 'C S', 'M', 'ECE' */
    code: string;
    /** The human readable name of the field of study */
    name: string;
};

/**
 * Fields of study offered in UT's course schedule, taken from the field of study search on the registrar's results page.
 *
 * This is only a fallback for before the first search, every search refreshes the list from UT
 * (see `parseFieldsOfStudy` in `views/lib/courseFinder.ts`).
 */
export const FIELDS_OF_STUDY: readonly FieldOfStudy[] = [
    { code: 'A I', name: 'Artificial Intelligence' },
    { code: 'AAS', name: 'Asian American Studies' },
    { code: 'ACC', name: 'Accounting' },
    { code: 'ADV', name: 'Advertising' },
    { code: 'AED', name: 'Art Education' },
    { code: 'AET', name: 'Arts/Entertainment Technology' },
    { code: 'AFR', name: 'African/African Diaspora Studies' },
    { code: 'AFS', name: 'Air Force Science' },
    { code: 'AHC', name: 'Ancient History/Classical Civ' },
    { code: 'AMS', name: 'American Studies' },
    { code: 'ANS', name: 'Asian Studies' },
    { code: 'ANT', name: 'Anthropology' },
    { code: 'ARA', name: 'Arabic' },
    { code: 'ARC', name: 'Architecture' },
    { code: 'ARE', name: 'Architectural Engineering' },
    { code: 'ARH', name: 'Art History' },
    { code: 'ARI', name: 'Architectural Interior Design' },
    { code: 'ART', name: 'Art, Studio' },
    { code: 'ASE', name: 'Aerospace Engineering' },
    { code: 'ASL', name: 'American Sign Language' },
    { code: 'AST', name: 'Astronomy' },
    { code: 'AUD', name: 'Audiology' },
    { code: 'B A', name: 'Business Administration' },
    { code: 'BAH', name: 'Business Admin Honors' },
    { code: 'BAX', name: 'Business Analytics' },
    { code: 'BCH', name: 'Biochemistry' },
    { code: 'BDP', name: 'Bridging Disciplines' },
    { code: 'BGS', name: 'Business/Government/Society' },
    { code: 'BIO', name: 'Biology' },
    { code: 'BME', name: 'Biomedical Engineering' },
    { code: 'BSN', name: 'Bassoon' },
    { code: 'C C', name: 'Classical Civilization' },
    { code: 'C E', name: 'Civil Engineering' },
    { code: 'C L', name: 'Comparative Literature' },
    { code: 'C S', name: 'Computer Science' },
    { code: 'CDI', name: 'Critical Disability Studies' },
    { code: 'CGS', name: 'Cognitive Science' },
    { code: 'CH', name: 'Chemistry' },
    { code: 'CHE', name: 'Chemical Engineering' },
    { code: 'CHI', name: 'Chinese' },
    { code: 'CIV', name: 'Civics' },
    { code: 'CLA', name: 'Clarinet' },
    { code: 'CLD', name: 'Communication and Leadership' },
    { code: 'CMS', name: 'Communication Studies' },
    { code: 'COE', name: 'Computational Engineering' },
    { code: 'COM', name: 'Communication' },
    { code: 'CON', name: 'Conducting' },
    { code: 'CRP', name: 'Community/Regional Planning' },
    { code: 'CRW', name: 'Creative Writing' },
    { code: 'CSE', name: 'Computational Science/Engineering' },
    { code: 'CTI', name: 'Core Texts and Ideas' },
    { code: 'CZ', name: 'Czech' },
    { code: 'D B', name: 'Double Bass' },
    { code: 'D S', name: 'Decision Science' },
    { code: 'DAN', name: 'Danish' },
    { code: 'DCH', name: 'Dutch' },
    { code: 'DES', name: 'Design' },
    { code: 'DEV', name: 'Developmental Studies' },
    { code: 'DRS', name: 'Drum Set' },
    { code: 'DSC', name: 'Data Science' },
    { code: 'E', name: 'English' },
    { code: 'E M', name: 'Engineering Mechanics' },
    { code: 'E S', name: 'Engineering Studies' },
    { code: 'ECE', name: 'Electrical/Computer Engineering' },
    { code: 'ECO', name: 'Economics' },
    { code: 'EDC', name: 'Curriculum and Instruction' },
    { code: 'EDP', name: 'Educational Psychology' },
    { code: 'EDU', name: 'Education' },
    { code: 'EEB', name: 'Ecology, Evolution, and Behavi' },
    { code: 'EER', name: 'Energy and Earth Resources' },
    { code: 'ELP', name: 'Educational Leadership/Policy' },
    { code: 'ENM', name: 'Engineering Management' },
    { code: 'ENS', name: 'Ensemble' },
    { code: 'ESL', name: 'English as a Second Language' },
    { code: 'EUP', name: 'Euphonium' },
    { code: 'EUS', name: 'European Studies' },
    { code: 'EVE', name: 'Environmental Engineering' },
    { code: 'EVS', name: 'Environmental Science' },
    { code: 'F A', name: 'Fine Arts' },
    { code: 'F C', name: 'French Civilization' },
    { code: 'F H', name: 'French Horn' },
    { code: 'FIN', name: 'Finance' },
    { code: 'FLU', name: 'Flute' },
    { code: 'FR', name: 'French' },
    { code: 'G E', name: 'General Engineering' },
    { code: 'GEO', name: 'Geological Sciences' },
    { code: 'GER', name: 'German' },
    { code: 'GK', name: 'Greek' },
    { code: 'GOV', name: 'Government' },
    { code: 'GRG', name: 'Geography' },
    { code: 'GRS', name: 'Graduate School' },
    { code: 'GSD', name: 'German/Scandinavian/Dutch' },
    { code: 'GUI', name: 'Guitar' },
    { code: 'H E', name: 'Human Ecology' },
    { code: 'H S', name: 'Health and Society' },
    { code: 'HAR', name: 'Harp' },
    { code: 'HDF', name: 'Human Development/Family Sciences' },
    { code: 'HDO', name: 'Human Dimensions of Orgs' },
    { code: 'HEB', name: 'Hebrew' },
    { code: 'HED', name: 'Health Education' },
    { code: 'HHM', name: 'Humanities/Health/Medicine' },
    { code: 'HIN', name: 'Hindi' },
    { code: 'HIS', name: 'History' },
    { code: 'HMN', name: 'Humanities' },
    { code: 'I', name: 'Informatics' },
    { code: 'I B', name: 'International Business' },
    { code: 'ILA', name: 'Iberian/Latin American Langs' },
    { code: 'INB', name: 'Integrative Biology' },
    { code: 'INF', name: 'Information Studies' },
    { code: 'IRG', name: 'Intl Relations/Global Studies' },
    { code: 'ISP', name: 'Information Security/Privacy' },
    { code: 'ITC', name: 'Italian Civilization' },
    { code: 'ITD', name: 'Integrated Design' },
    { code: 'ITL', name: 'Italian' },
    { code: 'J', name: 'Journalism' },
    { code: 'J S', name: 'Jewish Studies' },
    { code: 'JPN', name: 'Japanese' },
    { code: 'KIN', name: 'Kinesiology' },
    { code: 'KOR', name: 'Korean' },
    { code: 'L A', name: 'Liberal Arts' },
    { code: 'LAH', name: 'Liberal Arts Honors' },
    { code: 'LAL', name: 'Latin American Languages, Indigenous' },
    { code: 'LAR', name: 'Landscape Architecture' },
    { code: 'LAS', name: 'Latin American Studies' },
    { code: 'LAT', name: 'Latin' },
    { code: 'LAW', name: 'Law' },
    { code: 'LEB', name: 'Legal Environment of Business' },
    { code: 'LIN', name: 'Linguistics' },
    { code: 'LTC', name: 'Language Teaching/Coordination' },
    { code: 'M', name: 'Mathematics' },
    { code: 'M E', name: 'Mechanical Engineering' },
    { code: 'M S', name: 'Military Science' },
    { code: 'MAL', name: 'Malayalam' },
    { code: 'MAN', name: 'Management' },
    { code: 'MAS', name: 'Mexican American Studies' },
    { code: 'MBS', name: 'Molecular Biosciences' },
    { code: 'MDV', name: 'Medieval Studies' },
    { code: 'MEL', name: 'Middle Eastern Langs/Cultures' },
    { code: 'MES', name: 'Middle Eastern Studies' },
    { code: 'MFG', name: 'Manufacturing Systems Eng' },
    { code: 'MIC', name: 'Microbiology' },
    { code: 'MIS', name: 'Management Information Systems' },
    { code: 'MKT', name: 'Marketing' },
    { code: 'MLS', name: 'Medical Laboratory Science' },
    { code: 'MNS', name: 'Marine Science' },
    { code: 'MOL', name: 'Molecular Biology' },
    { code: 'MSE', name: 'Materials Science/Engineering' },
    { code: 'MUS', name: 'Music' },
    { code: 'N', name: 'Nursing' },
    { code: 'N S', name: 'Naval Science' },
    { code: 'NEU', name: 'Neuroscience' },
    { code: 'NOR', name: 'Norwegian' },
    { code: 'NRP', name: 'Nurse Professional' },
    { code: 'NSC', name: 'Natural Sciences' },
    { code: 'NTR', name: 'Nutrition' },
    { code: 'O M', name: 'Operations Management' },
    { code: 'OBO', name: 'Oboe' },
    { code: 'OPR', name: 'Opera' },
    { code: 'ORG', name: 'Organ' },
    { code: 'ORI', name: 'Operations Rsrch/Industrial Engr' },
    { code: 'P A', name: 'Public Affairs' },
    { code: 'P B', name: 'Plant Biology' },
    { code: 'P L', name: 'Public Leadership' },
    { code: 'P R', name: 'Public Relations' },
    { code: 'P S', name: 'Physical Science' },
    { code: 'PBH', name: 'Public Health' },
    { code: 'PED', name: 'Physical Education' },
    { code: 'PER', name: 'Percussion' },
    { code: 'PGE', name: 'Petroleum/Geosystems Engineering' },
    { code: 'PGS', name: 'Pharmacy Graduate Studies' },
    { code: 'PHL', name: 'Philosophy' },
    { code: 'PHM', name: 'Pharmacy PharmD' },
    { code: 'PHY', name: 'Physics' },
    { code: 'PIA', name: 'Piano' },
    { code: 'POL', name: 'Polish' },
    { code: 'POR', name: 'Portuguese' },
    { code: 'PPE', name: 'Philosophy, Politics, and Econ' },
    { code: 'PRC', name: 'Portuguese Civilization' },
    { code: 'PRS', name: 'Persian' },
    { code: 'PSC', name: 'Prevention Science' },
    { code: 'PSY', name: 'Psychology' },
    { code: 'R E', name: 'Real Estate' },
    { code: 'R M', name: 'Risk Management' },
    { code: 'R S', name: 'Religious Studies' },
    { code: 'RBT', name: 'Robotics' },
    { code: 'REE', name: 'Russian/East European/Eurasian' },
    { code: 'RHE', name: 'Rhetoric and Writing' },
    { code: 'RIM', name: 'Race/Indigeneity/Migration' },
    { code: 'RTF', name: 'Radio-Television-Film' },
    { code: 'RUS', name: 'Russian' },
    { code: 'S C', name: 'Serbian/Croatian' },
    { code: 'S S', name: 'Social Science' },
    { code: 'S W', name: 'Social Work' },
    { code: 'SAN', name: 'Sanskrit' },
    { code: 'SAX', name: 'Saxophone' },
    { code: 'SDS', name: 'Statistics and Data Sciences' },
    { code: 'SED', name: 'Special Education' },
    { code: 'SEL', name: 'Slavic and Eurasian Languages' },
    { code: 'SLH', name: 'Speech/Language/Hearing Sciences' },
    { code: 'SOC', name: 'Sociology' },
    { code: 'SPB', name: 'Sports Production and Broadcas' },
    { code: 'SPC', name: 'Spanish Civilization' },
    { code: 'SPN', name: 'Spanish' },
    { code: 'SSE', name: 'Semiconductor Science and Engi' },
    { code: 'STA', name: 'Statistics' },
    { code: 'STC', name: 'Science/Technology Commerce' },
    { code: 'STM', name: 'Sci/Tech/Engr/Math Studies' },
    { code: 'SUS', name: 'Sustainability Studies' },
    { code: 'SWE', name: 'Swedish' },
    { code: 'T C', name: 'Tutorial Course' },
    { code: 'T D', name: 'Theatre and Dance' },
    { code: 'TAM', name: 'Tamil' },
    { code: 'TBA', name: 'Tuba' },
    { code: 'TRO', name: 'Trombone' },
    { code: 'TRU', name: 'Trumpet' },
    { code: 'TUR', name: 'Turkish' },
    { code: 'TXA', name: 'Textiles and Apparel' },
    { code: 'U D', name: 'Urban Design' },
    { code: 'UGS', name: 'Undergraduate Studies' },
    { code: 'UKR', name: 'Ukrainian' },
    { code: 'URB', name: 'Urban Studies' },
    { code: 'URD', name: 'Urdu' },
    { code: 'UTL', name: 'UTeach-Liberal Arts' },
    { code: 'UTS', name: 'UTeach-Natural Sciences' },
    { code: 'V C', name: 'Violoncello' },
    { code: 'VIA', name: 'Viola' },
    { code: 'VIO', name: 'Violin' },
    { code: 'VOI', name: 'Voice' },
    { code: 'WGS', name: "Women's and Gender Studies" },
    { code: 'WRT', name: 'Writing' },
    { code: 'YID', name: 'Yiddish' },
    { code: 'YOR', name: 'Yoruba' },
];
